# Generated by Django 3.2.8 on 2023-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20230708_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='helmet',
            field=models.IntegerField(default=0),
        ),
    ]
