# Generated by Django 3.2.8 on 2023-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_helmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
