# Generated by Django 3.2.8 on 2023-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='type_car',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
