# Generated by Django 3.2.8 on 2023-07-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_consecutive'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='consecutive',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
