# Generated by Django 3.2.8 on 2023-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_schedule_consecutive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='entrance',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exit',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
