# Generated by Django 3.2.8 on 2023-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20230726_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='entrance',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='exit',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
