# Generated by Django 3.2.8 on 2023-07-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_type_user'),
        ('parking_lot', '0001_initial'),
        ('car', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance', models.DateTimeField()),
                ('exit', models.DateTimeField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parking_lot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
