# Generated by Django 3.2.8 on 2023-07-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_history_schedule_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_schedule',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
